In [3]:
def msg(x):
    return x+5

out=msg(5)
print(out)

10


In [9]:
def msg(x):
    return x+5


print(msg(500))

505


In [10]:
out=lambda x:x+5
out(500)

505

In [18]:
for i in range(1,11):
    y=lambda x:x*2
  

    print(y(i))

2
4
6
8
10
12
14
16
18
20


In [19]:
for i in range(1,11):
    y=lambda x:x*5
    print(y(i))

5
10
15
20
25
30
35
40
45
50


In [21]:
y=lambda x,y:x*y
print(y(2,10))
print("hello")

20
hello


In [24]:
mylist=["hello","hey"]
print(len(mylist))
list(map(len,mylist))

2


[5, 3]

In [32]:
x=[2,5,5,6,5]
def msg(x):
    return x**2

list(map(msg , x))

[4, 25, 25, 36, 25]

In [33]:
list(map(lambda x:x**2 ,x))

[4, 25, 25, 36, 25]

In [39]:
newlist=[]
x=[2,5,5,6,5]

for i in range(2,5):
    newlist.append(i+50)

print(newlist)

[52, 53, 54]


In [45]:
[i+50 for i in range(2,5)]

[52, 53, 54]

In [16]:
x=1
for i in range(1,4):
    for k in range(5-i):
        print(x,end=" ")
        x=x+1
    for j in range(i):
        print("*",end=" ")
    print()


1 2 3 4 * 
5 6 7 * * 
8 9 * * * 


In [18]:
import numpy as np
a=[1,2,3,4]
type(a)

list

In [20]:
b=np.array(a)
a
b

array([1, 2, 3, 4])

In [21]:
type(b)

numpy.ndarray

In [30]:
x=[]
a=int(input("size of array:"))
for i in range(a):
    y=int(input("enter input:"))
    x.append(y)


b=np.array(x)
b

size of array: 2
enter input: 2
enter input: 1


array([2, 1])

In [31]:
a = [] 
size = int(input("Enter size:"))
for i in range(size):
    val = int(input("Enter item:"))
    a.append(val) 
b = np.array(a) 
b

Enter size: 2
Enter item: 4
Enter item: 5


array([4, 5])

In [32]:
b

array([4, 5])

In [33]:
a=[225,5,3,64,46,4]

b=np.array(a)
b

array([225,   5,   3,  64,  46,   4])

In [34]:
b.shape

(6,)

In [35]:
b.size

6

In [50]:
a=[[1,2,3],[4,8,1],[1,2,3]]
b=np.array(a)
b.shape
b.size

9

In [52]:
a=np.zeros(4)
a

array([0., 0., 0., 0.])

In [53]:
a=np.zeros((2,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:

a=np.ones((2,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [56]:

a=np.twos((2,10))
a

AttributeError: module 'numpy' has no attribute 'twos'

In [58]:

a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [59]:
a=np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [66]:
x=1
for i in range(1,5):
    for k in range(5-i):
        print("*",end=" ")
        
    for j in range(i):
        print(x,end=" ")
        x=x+1
    print()

* * * * 1 
* * * 2 3 
* * 4 5 6 
* 7 8 9 10 


In [71]:
import numpy as np
a=np.diag([3,4,5,5,4])
a

array([[3, 0, 0, 0, 0],
       [0, 4, 0, 0, 0],
       [0, 0, 5, 0, 0],
       [0, 0, 0, 5, 0],
       [0, 0, 0, 0, 4]])

In [74]:
import numpy as np
a=np.random.randint(1,50,12)
a

array([1, 1, 1, 1, 1])

In [75]:
import numpy as np
a=np.random.rand(5)
a

array([0.28212763, 0.45400461, 0.63290984, 0.33069908, 0.99389801])

In [76]:
import numpy as np
a=np.random.randn(5)
a

array([-0.75614122, -0.76599741,  0.51182663,  0.75728567,  1.47216305])

In [77]:
import numpy as np
a=np.random.randint(1,50,12)
a

array([14, 38, 18, 32, 26, 14, 21,  4, 23, 34,  6, 43])

In [78]:
a.shape

(12,)

In [81]:
a=a.reshape(2,6)
a

array([[14, 38, 18, 32, 26, 14],
       [21,  4, 23, 34,  6, 43]])

In [82]:
a=a.reshape(4,3)
a

array([[14, 38, 18],
       [32, 26, 14],
       [21,  4, 23],
       [34,  6, 43]])

In [85]:
a=a.reshape(-1,4)
a

array([[14, 38, 18, 32],
       [26, 14, 21,  4],
       [23, 34,  6, 43]])

In [86]:
# 2
a=[1,2,5,6]
b=np.array(a)
b

array([1, 2, 5, 6])

In [89]:
# 3
newlist=[]
for i in range(10):
    y=int(input("enter item:"))
    newlist.append(y)

c=np.array(newlist)
c



enter item: 5
enter item: 4
enter item: 5
enter item: 54
enter item: 5
enter item: 21
enter item: 2
enter item: 2
enter item: 2
enter item: 2


array([ 5,  4,  5, 54,  5, 21,  2,  2,  2,  2])

In [92]:
# 4
import numpy as np

a=np.random.randint(10,20,10)
a

array([14, 19, 19, 15, 16, 16, 14, 17, 16, 13])

In [93]:
# 5
a=np.full(10,5)
a

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [97]:
a=[[1,2,3],[2,5,6],[5,5,8]]
b=np.array(a)
b


array([[1, 2, 3],
       [2, 5, 6],
       [5, 5, 8]])

In [95]:
b.ndim

2

In [102]:
import numpy as np 
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6] 
b[:] = 0 
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [99]:
matrix.ndim

2

In [103]:
import numpy as np 
a = np.array([10 , 20 , 30 , 40 , 50 , 60 , 70 , 80 ])
b = a[3:6].copy()
b[:] = 0 
a

array([10, 20, 30, 40, 50, 60, 70, 80])

In [104]:
b

array([0, 0, 0])

In [108]:
a=np.arange(2,15)
a

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [109]:
a>10

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True])

In [110]:
a==10

array([False, False, False, False, False, False, False, False,  True,
       False, False, False, False])

In [112]:
b=a>10
a[b]

array([11, 12, 13, 14])

In [113]:
np.min(a)

2

In [114]:
np.max(a)

14

In [115]:
np.argmin(a)

0

In [116]:
np.argmax(a)

12